### ISSUE TITLE
How to install with pip

### ISSUE THREAD

**Issue by mw44118** [abesto/yq#1]
You want help writing a setup.py?

**Comment by abesto** [comment]
Honestly, I didn't think there's interest :) Plus, it looks like the current architecture can't accomodate the more advanced features of `jq`. Maybe it'd be better to write a wrapper around `jq`, or implement YAML support on `jq` itself, see https://github.com/stedolan/jq/issues/467

That said, if you write up a `setup.py`, I'll be happy to merge it. Even upload it to PyPI.

**Comment by SamuelMarks** [comment]
@abesto Here ya go mate, well an attempt anyway: https://github.com/abesto/yq/pull/2

**Comment by abesto** [comment]
You can now just `pip install yq`.

For the record, you may be better off using the `yq` provided by https://github.com/wildducktheories/y2j, but if you need a pure python implementation, you can now install this project easily.
