### ISSUE TITLE
Make homebrew package

### ISSUE THREAD

**Issue by ahmetb** [abesto/yq#5]
It'd be handy to install it as `brew install yq` or something.

**Comment by abesto** [comment]
Hey @ahmetalpbalkan, you may want to take a look at the yq tool provided by https://github.com/wildducktheories/y2j. It wraps jq, so is completely full-featured (unlike this project). Do you need a pure python implementation for some reason?

**Comment by ahmetb** [comment]
Heh came here to open the same issue again. I guess y2j would solve my problem.
