### ISSUE TITLE
PyPI package name

### ISSUE THREAD

**Issue by kislyuk** [abesto/yq#6]
Hello,

I would like to provide a lightweight Python package that accomplishes the role of "jq for YAML documents" in a minimalistic way by transcoding YAML to JSON and piping it through jq. For that purpose it would be useful to be able to publish to the "yq" package name on PyPI.

Since you are not intending to maintain this package further, I was wondering if you'd be interested in transferring the package name to me.

Thanks!

**Comment by abesto** [comment]
Hey @kislyuk, that sounds like a great idea.

Only thing I want to make sure is that any potential active users don't have their stuff broken overnight. The easy part is renaming this package to `py-yq` or something like that (or maybe just not having it on pypi at all).

The hard part is signalling that this is a potentially BC-breaking replacement of the full implementation. A major version bump could be one way, but I guess you wouldn't want to publish 1.0.0 right away? But then we can only do a minor version bump, which totally breaks semver.

Worst case, we can just bite the bullet and replace the package with a minor version bump and a big loud notice in the readme. What do you think?

**Comment by kislyuk** [comment]
My proposal would be to begin my release series with v2.0.0 to comply with semver and avoid any ambiguity about the meaning of "v1.0.0". I would also put together a disclaimer about backwards compatibility in the readme/pypi/docs.

**Comment by abesto** [comment]
Sounds good, let's do that. Let me know your pypi username, and I'll make you an owner of the package - you can go ahead and make the changes without blocking on me.

Thank you, this is making the world a better place :)

**Comment by kislyuk** [comment]
My PyPI username is kislyuk. Thank you!

**Comment by abesto** [comment]
And done. Go forth and do good! ;)

Also, feel free to remove me as "owner" once all is set.

**Comment by kislyuk** [comment]
New package is up at https://pypi.python.org/pypi/yq!
